### ISSUE TITLE
Formatar a Tela inicial do Wiki.

### ISSUE THREAD

**Issue by mauricio-monteiro** [ifmg-betim/2020.2-pootw#1]
É necessário criar a tela inicial do Wiki separando as documentações geradas pelas equipes na tela inicial do Wiki.

**Comment by mauricio-monteiro** [comment]
Isso mesmo toda documentção deve ser adicionada no Wiki. 👍

**Comment by jordeao** [comment]
Realizada a organização dos temas que ja temos. De acordo com que forem surgindo novos temas, será feita esta organização
Tarefa concluida.
