### ISSUE TITLE
Adicionar informações a Tarefa

### ISSUE THREAD

**Issue by mauricio-monteiro** [ifmg-betim/2020.2-pootw#11]
Está faltando para quem é a tarefa e demais coisas na atividade. #4

**Comment by mauricio-monteiro** [comment]
@ifmg-betim/2020_2_pootw_sputnik Atenção todos, todos os bugs devem ser solucionados, pois o mesmo geram perda de pontos.

1 ponto para cada bugs não fechado.

Mesmo a atividade estando direcionado a @Viniomm não significa que só ele deve corrigir.

O bug pertence a equipe então todos da equipe perdem ponto.

Fiquem ligados.

👌

**Comment by Viniomm** [comment]
Os dados foram inseridos.
