### ISSUE TITLE
Definir plataforma de consulta dos dados

### ISSUE THREAD

**Issue by gaabrielreis** [ifmg-betim/2020.2-pootw#13]
Devo desenvolver uma página web ou posso usar alguma plataforma pronta de consulta?

**Comment by mauricio-monteiro** [comment]
Mas construir baseando qual requisito? OU seja, você já sabe todo contexto do que será construido?

Se sim, então antes deve documentar os requisisto de tal forma compartilhar com toda equipe para que o software a ser construído seja visto de vários pontos de vista.
