### ISSUE TITLE
Realizar o Levantamento dos Requisitos.

### ISSUE THREAD

**Issue by mauricio-monteiro** [ifmg-betim/2020.2-pootw#14]
A equipe deve realizar o levantamento de requisitos funcionais e não funcionais do projeto.

Adicionando o mesmo no Wiki do Repositórios GitHub.

**Comment by gaabrielreis** [comment]
Adicionado no Wiki um pouquinho da história do projeto do cliente, os requisitos funcionais e não funcionais .

**Comment by gaabrielreis** [comment]
Link para acessar o wiki como o levantamento [https://github.com/ifmg-betim/2020.2-pootw.wiki.git](url)
