### ISSUE TITLE
Relembrando markdown

### ISSUE THREAD

**Issue by israel0410** [ifmg-betim/2020.2-pootw#17]
Aprender\Relembrar de como se trabalhar dom Markdown

**Comment by mauricio-monteiro** [comment]
@israel0410, sempre adicionei um comentário na Issue, para ficar melhor explicado sobre o que se trata a atividade que está sendo feita.

👌

**Comment by israel0410** [comment]
#markdown 
## Importacia

auxilia na edição de texto e facilita a formatação.
[code fonte tv](https://www.youtube.com/watch?v=gFJfyHRKaE0)

**Comment by mauricio-monteiro** [comment]
@israel0410 Adionei esselink que postou aqui nos comentários da issue. Lá no Wiki, para auxiliar todos.

**Comment by jordeao** [comment]
Tarefa realizada.
