### ISSUE TITLE
CONTROLE DE VERSÃO

### ISSUE THREAD

**Issue by dionatandiego11** [ifmg-betim/2020.2-pootw#19]
Fazer Download e instalar o  GIT.

https://git-scm.com/download/win

**Comment by leoolucas** [comment]
Instalado, junto com o Visual Code

**Comment by mauricio-monteiro** [comment]
Isso aí está certinho.... Registrando sua atividade.

**Comment by viniciusfernansilva** [comment]
VS e Git instalados

**Comment by mauricio-monteiro** [comment]
Todos já conseguiram???

Não esqueção de escrever o passo feitos no Wiki.

**Comment by Viniomm** [comment]
O Git, VSCode e Mozilla Firefox forma instalados.

**Comment by vandersonama** [comment]
Como todos já instalaram o GIT e VS Code vou fechar essa issue.
