### ISSUE TITLE
Marcar encontro para alinhamento das atividades

### ISSUE THREAD

**Issue by gaabrielreis** [ifmg-betim/2020.2-pootw#22]
Sábado ás 9:00.

**Comment by gaabrielreis** [comment]
Nesse encontro, vamos bater um papo com o nosso cliente para levantamento dos requisitos do software.

**Comment by gaabrielreis** [comment]
Vamos eleger um stakeholder.

**Comment by mauricio-monteiro** [comment]
Ótimo! Lembrando que eu @mauricio-monteiro sou um dos stakeholder.

👍

**Comment by gaabrielreis** [comment]
Nesse encontro foi alinhado a ideia do projeto Fill e realizamos o levantamento de requisitos. Interessante alinharmos com o @mauricio-monteiro.
