### ISSUE TITLE
Instalação e configuração do ambiente

### ISSUE THREAD

**Issue by gaabrielreis** [ifmg-betim/2020.2-pootw#23]
Realizar testes em alguns ambientes apresentados para definir qual será o melhor para o desenvolvimento do projeto.

**Comment by mauricio-monteiro** [comment]
Sempre adicione comentário na abertura da Issue.

👀

**Comment by ctnalves** [comment]
VS Code instalado 
Falta instalar e fazer testes do Gib no Windows.

**Comment by gaabrielreis** [comment]
Testes realizado com sucesso na plataforma VsCode com iterações diretas do Git.
