### ISSUE TITLE
Instalar e configurar Linux, com firefox e Visual Code

### ISSUE THREAD

**Issue by jordeao** [ifmg-betim/2020.2-pootw#24]
Realizar a instalação e configuração do Linux, com Firefox e Visual Studio Code 
.

**Comment by mauricio-monteiro** [comment]
Precisando de Ajuda em qual ponto?

**Comment by mauricio-monteiro** [comment]
Vejo que não preciso estar atuando diretamente nessa atividade.

**Comment by jordeao** [comment]
Realizado a instalação e configuração dos mesmos. 
Atividade concluída
