### ISSUE TITLE
Postar video aula do dia 20/08/2020 no AVA

### ISSUE THREAD

**Issue by jordeao** [ifmg-betim/2020.2-pootw#25]

**Comment by mauricio-monteiro** [comment]
Video Postado!

![image](https://user-images.githubusercontent.com/23531545/91174524-c8c45300-e6b5-11ea-82b1-71bb73fa87c7.png)

Isso aí, fez certinho arndo a Issue.

Lembrando que não deve esquecer de colocar o Projeto e Milestone na abertura da atividade, se não sabe qual Milestone, coloque no Milestone "Outros"

**Comment by mauricio-monteiro** [comment]
Atvidade concluída.
