### ISSUE TITLE
CONFIGURAÇÃO HARWARE

### ISSUE THREAD

**Issue by dionatandiego11** [ifmg-betim/2020.2-pootw#29]
Para documentação, todos deverão especificar as configurações de suas máquinas:

- Processador
- Memória RAM
- Disponibilidade de memoria massiva
- Placa gráfica

**Comment by viniciusfernansilva** [comment]
Processador: Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz 3.00GHz
Memoria RAM; 8,00GB
Placa; NVIDIA GeForce GT 630

**Comment by Viniomm** [comment]
Pra termos de futura anotação em outros lugares como a criação de uma wiki vou deixar aqui como comentário:
Estou utilizando somente o computador da empresa pra ter tudo em um lugar só (pode ser que eu precise de mudar para um pessoal em algum momento, mas creio que não acontecerá), sendo assim as configurações dele são: Intel Core i7 (8th Gen), 16GB de RAM sendo 15,9GB utilizáveis, somente um SSD de 292GB (porém aprox. 60GB disponíveis), Windows 10 Pro 64 Bits e placa gráfica nativa.

**Comment by vandersonama** [comment]
Processador: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz 2.50GHz
Memoria RAM; 4,00GB
Sistema operacional 64 bits
Placa: Intel(R) HD Graphics 3000

**Comment by dionatandiego11** [comment]
**Processador:** Intel(R) Celeron, N3060, CPU @1.60 GHz aumento  2.48 GHz
**Memoria RAM:** 4,00GB
**Sistema operacional:** Windows 10, 64 bits
**Placa:** Intel(R) HD Graphics
**HD:** 500GB

**Comment by dionatandiego11** [comment]
Finalizado!
