### ISSUE TITLE
Disponibilizar aquivo ".bashrc"

### ISSUE THREAD

**Issue by dionatandiego11** [ifmg-betim/2020.2-pootw#30]
@mauricio-monteiro não encontrei o arquivo ".bashrc" na pasta indicada, crie no bash, preciso do conteúdo interno, o Sr poderia disponibilizar, por favor?!.

**Comment by mauricio-monteiro** [comment]
@dionatandiego11 tem que colocar assifne para mim.

**Comment by dionatandiego11** [comment]
@mauricio-monteiro perdão, já resolve.

**Comment by mauricio-monteiro** [comment]
# Esse é meu .bashrc:


alias code="code --extensions-dir .extensions"
alias edit="/c/Program\ Files\ \(x86\)/Notepad++/notepad++.exe"

alias ll="ls -lhF"
alias gs="git status"

export PATH=""

export PATH="$PATH:/c/Users/Mauricio Monteiro/bin"
export PATH="$PATH:/mingw64/bin"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/bin"

export PATH="$PATH:/c/cygwin64/bin"
export PATH="$PATH:/c/cygwin64/sbin"

export PATH="$PATH:/c/WINDOWS/system32"
export PATH="$PATH:/c/WINDOWS"
export PATH="$PATH:/c/WINDOWS/System32/Wbem"
export PATH="$PATH:/c/WINDOWS/System32/WindowsPowerShell/v1.0"
export PATH="$PATH:/c/WINDOWS/System32/OpenSSH"

export PATH="$PATH:/c/Program Files/PuTTY"

export PATH="$PATH:/c/texmaker-home/MiKTeX2.9/miktex/bin/x64"
export PATH="$PATH:/c/MiKTeX/miktex/bin/x64"

export PATH="$PATH:/c/nodejs"
export PATH="$PATH:/c/Users/Mauricio Monteiro/AppData/Roaming/npm"
export PATH="$PATH:/c/MinGW/bin"

export PATH="$PATH:/c/Program Files/Microsoft VS Code/bin"
export PATH="$PATH:/c/Program Files/Microsoft VS Code"

export PATH="$PATH:/c/python-home/Python37"
export PATH="$PATH:/c/python-home/Python37/Scripts"

export PATH="$PATH:/c/caddy-home/caddy_v1.0.4"

export PATH="$PATH:/c/Program Files/Firefox Developer Edition"

export PATH="$PATH:/c/Program Files (x86)/DOSBox-0.74-3"

export PATH="$PATH:/c/Program Files (x86)/Graphviz2.38/bin"

export PATH="$PATH:/c/ProgramData/DockerDesktop/version-bin"

export PATH="$PATH:/c/Program Files/Docker/Docker/resources/bin"

export PATH="$PATH:/c/Nmap"

export DENO_INSTALL="/c/Users/Mauricio Monteiro/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

**Comment by mauricio-monteiro** [comment]
Basta criar um arquivo texto na sua pasta pessoal.
