### ISSUE TITLE
Aguardando avaliação dos requisitos levantados

### ISSUE THREAD

**Issue by gaabrielreis** [ifmg-betim/2020.2-pootw#32]
Após realizar o levantamento de requisitos e história do cliente precisamos de uma avaliação se esta seguindo o proposta

- [x] Check

**Comment by ctnalves** [comment]
@mauricio-monteiro a wiki que escrevemos está de acordo com o esperado?

**Comment by mauricio-monteiro** [comment]
Bem O levantamento de Requisitos está ok!

Falta apenas fecharmos os User Stories.

**Comment by gaabrielreis** [comment]
Obrigado @mauricio-monteiro !
