### ISSUE TITLE
Estudar sobre Web Crawler

### ISSUE THREAD

**Issue by leoolucas** [ifmg-betim/2020.2-pootw#36]
Estudo sobre Web Crawlers com o objetivo de entender o melhor modo de busca de informações do TripAdvisor.

**Comment by viniciusfernansilva** [comment]
Iniciando estudos juntamente com o Leonardo sobre Web Crawlers

**Comment by leoolucas** [comment]
Testando a melhor maneira de utilizar o Web Crawler juntamente com outros bots locais de controle dos dados de cada restaurante.

Será montada uma versão Alpha da aplicação para análise juntamente da cliente com o objetivo de fechar o escopo do projeto e começar o desenvolvimento.

Está versão está em fase de testes, faltando somente a implementação do Web Crawler.

**Comment by leoolucas** [comment]
@mauricio-monteiro Estou com duvidas de como buscar o valor de um <span> utilizando o puppeteer.

Se puder responder aqui com um exemplo, seria ótimo.

await page.waitForSelector('div.geo_name > a');

 var stories = await page.evaluate(() => {
   var res = Array.from(document.querySelectorAll('div.geo_name > a'))
   return res.map(link => link.text)
 })

utilizando "text" não está funcionando

**Comment by leoolucas** [comment]
resolvido !

var nome = await page.evaluate(() => 
    document.querySelector('div.maincontent > h1').textContent
  )
