### ISSUE TITLE
Exemplo storys

### ISSUE THREAD

**Issue by dionatandiego11** [ifmg-betim/2020.2-pootw#46]
@mauricio-monteiro poderia compartilhar link do projeto do semestre passado, para nós usarmos de exemplo os "storys" deles? Obrigado.

**Comment by mauricio-monteiro** [comment]
@dionatandiego11 o projeto do semestre passado está no Gitlab.

Basta acessar o link:

[https://gitlab.com/ifmg-betim/disciplinas/pootw/controla-lanche/-/wikis/home](https://gitlab.com/ifmg-betim/disciplinas/pootw/controla-lanche/-/wikis/home)
