### ISSUE TITLE
Como associar uma issue em um comite de outra issue?

### ISSUE THREAD

**Issue by gaabrielreis** [ifmg-betim/2020.2-pootw#49]
Melhorar comentários a ser realizados

**Comment by gaabrielreis** [comment]
@mauricio-monteiro ajuda aí!

**Comment by gaabrielreis** [comment]
Solução encontrada!

**Comment by mauricio-monteiro** [comment]
Segue Abaixo um imagem com a explicação do uso de referencia ao commit.

![image](https://user-images.githubusercontent.com/23531545/92528459-2d77c580-f1ff-11ea-8eed-7a46009d54bd.png)

Veja se a informação é suficiente para lhe auxiliar.
