### ISSUE TITLE
Trabalho, Mauricio.

### ISSUE THREAD

**Issue by dionatandiego11** [ifmg-betim/2020.2-pootw#7]
Utilizar por uma aula o Internet Explorer.

**Comment by mauricio-monteiro** [comment]
😂😂

**Comment by mauricio-monteiro** [comment]
Atividade concluída. Foi ministrada uma aula com a turma de Introdução a Informática onde mostrei o quando usar o IE é arriscado na internet e como tal plataforma sempre trás problemas para vida dos seres humanos.
